### ISSUE TITLE
colors of patterns in p-strip--accent

### ISSUE THREAD

**Issue by pmahnke** [vanilla-framework/vanilla-brochure-theme#82] opened 2017-06-04 16:47 UTC
## Process

1. place elements in .p-strip--accent, like buttons and p-card--highlighted

## Expected result

* colours of the text and backgrounds to invert or change

## Current result

* no change, and often the text is unreadable

## Screenshot

[If relevant, include a screenshot]

## Sample corrective code

```scss
  // XXX issue with colors for cards in a strip--accent
  .p-strip--accent {
    .p-card--highlighted {
      color: $color-mid-dark;

      a:link,
      a:visited {
        color: $color-brand;
      }

      a:hover,
      a:active {
        color: $color-brand;
        text-decoration: underline;
      }
    }
  }
```

**Comment by anthonydillon** [comment] 2017-06-05 00:31
My recommended solution for this would be to set the color of the effected children patterns. Not tightly couple two patterns. 

For example, the card-highlighed sets the background. Therefore it is safe to at the colour too.

**Comment by yaili** [comment] 2017-06-05 14:02
Marking as proposal, but let me know if it's not.

**Comment by yaili** [comment] 2017-06-09 12:48
Notes from working group:
- The proposed solution means the pattern would be changed by the parent pattern, which we should avoid
- We've decided that the patterns should be decoupled from each other
- The design spec should include text colour (card pattern)

**Comment by yaili** [comment] 2017-07-04 10:10
@barrymcgee would you say this is a duplicate of https://github.com/vanilla-framework/vanilla-framework/issues/1113 ?

**Comment by barrymcgee** [comment] 2017-07-04 10:17
@yaili No, they're similar but slightly different and both valid.

**Comment by yaili** [comment] 2017-07-04 10:52
@barrymcgee but doesn't the solution of 1113 solve this one? Is it what @anthonydillon is referring to in his comment above too?

**Closed** 2017-07-19 15:42 UTC
Labels: Priority: High, Status: Review, Type: Bug

**Comment by barrymcgee** [comment] 2017-07-19 16:29
This has now been addressed upstream by https://github.com/vanilla-framework/vanilla-framework/pull/1191
